version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin-easydine_frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge