GET http://localhost:3000/

###
# Tạo user mới
POST http://localhost:3000/signup
Content-Type: application/json

{
"role": "customer",
"name": "John Doe",
"address": "123 Main St, New York, NY",
"bio": "A passionate customer and long-time user.",
"gmail": "john.doe@gmail.com",
"phone": "0901234567",
"username": "johndoe",
"password": "hashed_password_example1"
}
###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "levanc",
  "password": "mypassword"
}