name: Deploy EasyDine Frontend to Ubuntu Server

on:
  push:
    branches:
      - vite-migration
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Build Frontend
        env:
          CI: false
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_MINIO_API_URL: ${{ secrets.VITE_MINIO_API_URL }}
        run: |
          npm install
          npm run build
          ls -la dist

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            if ! docker image inspect nginx:alpine3.20 >/dev/null 2>&1; then
              if [ -f /home/aris/nginx-alpine3.20.tar ]; then
                docker load -i /home/aris/nginx-alpine3.20.tar
              else
                docker pull nginx:alpine3.20
              fi
            fi
            if ! docker network inspect admin-easydine >/dev/null 2>&1; then
              docker network create admin-easydine
            fi
            cd /home/aris/admin-easydine
            git pull origin vite-migration
            rm -rf dist
            mkdir -p dist

      - name: Copy Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./dist/*"
          target: "/home/aris/admin-easydine/dist"

      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/aris/admin-easydine
            docker-compose down
            docker-compose up -d --build --force-recreate
            docker image prune -f
            ls -la dist

      - name: Check Frontend Health
        run: |
          sleep 30
          curl -f http://${{ secrets.SERVER_IP }}:3000 || exit 1